### ISSUE TITLE
Run into error when using Object.assign

### ISSUE THREAD

**Issue by pveyes** [babel/babel-jest#10]
Using `let` and ES6 class seems fine, but somehow I can't use `Object.assign`

I can use `Object.assign` on `babel-node` REPL though

Here's the stack trace (not sure if it helps)
```js
  - TypeError: Object function Object() { [native code] } has no method 'assign'
        at Spec.<anonymous> (/home/fatih/projects/virtualc/signal/__tests__/client-test.js:10:36)
        at jasmine.Block.execute (/home/fatih/projects/virtualc/signal/node_modules/jest-cli/vendor/jasmine/jasmine-1.3.0.js:1065:17)
        at jasmine.Queue.next_ (/home/fatih/projects/virtualc/signal/node_modules/jest-cli/vendor/jasmine/jasmine-1.3.0.js:2098:31)
        at null._onTimeout (/home/fatih/projects/virtualc/signal/node_modules/jest-cli/vendor/jasmine/jasmine-1.3.0.js:2088:18)
        at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```

**Comment by sebmck** [comment]
Yeah, you need to use the [polyfill](http://babeljs.io/docs/usage/polyfill/) as babel can't possibly transpile those kind of things without a polyfill/runtime.
