### ISSUE TITLE
Error thrown when `collectCoverage:true`

### ISSUE THREAD

**Issue by craigdallimore** [babel/babel-jest#11]
Hi, I'm having a bit of trouble using `babel-jest` with the [new coverage feature](https://github.com/facebook/jest/pull/178) in `jest`, on a React component written in ES6/JSX with an ES6 testfile.

I'm not sure if this issue belongs here, with [babel](https://github.com/babel/babel.github.io), with the [Jest repo](https://github.com/facebook/jest) (or even [istanbul](https://github.com/gotwarlost/istanbul)?). Looks like a similar issue has been discussed [here](https://github.com/gotwarlost/istanbul/issues/94).

I suspect it is something to do with the way `istanbul` maps line numbers between actual and instrumented files - possibly the JSX transformation is interfering.

I've made a crude [gist](https://gist.github.com/craigdallimore/546619f9c14fdda3d866) that reproduces the issue, with this outcome:

```
$ npm test

Using Jest CLI v0.4.0
 PASS  __tests__/component.test.js (2.108s)
1 test passed (1 total)
Run time: 2.451s
-------------------------------------------|-----------|-----------|-----------|-----------|
File                                       |   % Stmts |% Branches |   % Funcs |   % Lines |
-------------------------------------------|-----------|-----------|-----------|-----------|
   babel-jest-coverage/                    |       100 |       100 |       100 |       100 |
      component.jsx                        |       100 |       100 |       100 |       100 |
   babel-jest-coverage/node_modules/react/ |       100 |       100 |       100 |       100 |
      addons.js                            |       100 |       100 |       100 |       100 |
-------------------------------------------|-----------|-----------|-----------|-----------|
All files                                  |       100 |       100 |       100 |       100 |
-------------------------------------------|-----------|-----------|-----------|-----------|

Failed with unexpected error.

/home/decoy/dev-local/babel-jest-coverage/node_modules/jest-cli/src/jest.js:179
      throw error;
            ^
TypeError: Cannot set property 'covered' of undefined
```

**Comment by sebmck** [comment]
Yeah, looks very similar if not the same to gotwarlost/istanbul#94. Looks like Istanbul is being passed the transformed source and when it's trying to match up the line numbers it's throwing a tantrum because the input it was given doesn't match the original source as it's been transformed.

**Comment by craigdallimore** [comment]
@sebmck thanks for taking a look. Do you think this is an issue that should be solved in `babel-jest`, `istanbul` or `jest-cli`?

For anyone after a quick workaround, an alternative is to make a preprocessor file that uses [react-tools](https://www.npmjs.com/package/react-tools) like so:

*package.json*
```
"jest": {
    "scriptPreprocessor": "./preprocessor.js",
    ...
},
"dependencies": {
    "react-tools": "*",
    ...
}
...
```

*preprocessor.js*
```
var ReactTools = require('react-tools');
module.exports = {
  process: function(src) {
    return ReactTools.transform(src, { harmony: true });
  }
};
```

**Comment by sebmck** [comment]
I'm not sure, seems like it would be in `jest-cli`, I'm not sure if there's a way to fix it in `babel-jest` as it's unrelated.

**Comment by craigdallimore** [comment]
Ok, I'll close this and have a poke around in `jest-cli`.

**Comment by sebmck** [comment]
Great, thanks!

**Comment by hotzenklotz** [comment]
@craigdallimore Did you ever find a fix for this? I just ran into the exact same issue.

**Comment by craigdallimore** [comment]
@hotzenklotz no, not yet. I haven't raised an issue at the `jest-cli` repo either, let me know if you do.

**Comment by jehoshua02** [comment]
@hotzenklotz @craigdallimore I just ran into this issue as well. Wondering what if anything I can do to help fix it.

The issue can reproduced by following these precise steps:

```shell
git clone https://github.com/jehoshua02/react-scaffold.git
cd react-scaffold
npm install
npm test -- --coverage
```

And I get this output:

```shell
~/projects/jehoshua02/react-scaffold 🚀  babel_jest
$ npm test -- --coverage

> react-scaffold@1.0.0 test /Users/employee/projects/jehoshua02/react-scaffold
> jest --coverage

Using Jest CLI v0.4.0
 PASS  __tests__/sum-test.js (0.682s)
 PASS  __tests__/Hello.js (1.048s)
2 tests passed (2 total)
Run time: 1.971s
-----------------------|-----------|-----------|-----------|-----------|
File                   |   % Stmts |% Branches |   % Funcs |   % Lines |
-----------------------|-----------|-----------|-----------|-----------|
   app/components/     |       100 |       100 |       100 |       100 |
      Hello.js         |       100 |       100 |       100 |       100 |
   app/util/           |       100 |       100 |       100 |       100 |
      sum.js           |       100 |       100 |       100 |       100 |
   node_modules/react/ |       100 |       100 |       100 |       100 |
      addons.js        |       100 |       100 |       100 |       100 |
-----------------------|-----------|-----------|-----------|-----------|
All files              |       100 |       100 |       100 |       100 |
-----------------------|-----------|-----------|-----------|-----------|

Failed with unexpected error.

/Users/employee/projects/jehoshua02/react-scaffold/node_modules/jest-cli/src/jest.js:179
      throw error;
            ^
TypeError: Cannot set property 'covered' of undefined
  at /Users/employee/projects/jehoshua02/react-scaffold/node_modules/jest-cli/node_modules/istanbul/lib/report/html.js:175:66
  at Array.forEach (native)
  at annotateLines (/Users/employee/projects/jehoshua02/react-scaffold/node_modules/jest-cli/node_modules/istanbul/lib/report/html.js:173:28)
  at HtmlReport.Report.mix.writeDetailPage (/Users/employee/projects/jehoshua02/react-scaffold/node_modules/jest-cli/node_modules/istanbul/lib/report/html.js:406:9)
  at /Users/employee/projects/jehoshua02/react-scaffold/node_modules/jest-cli/node_modules/istanbul/lib/report/html.js:472:26
  at SyncFileWriter.extend.writeFile (/Users/employee/projects/jehoshua02/react-scaffold/node_modules/jest-cli/node_modules/istanbul/lib/util/file-writer.js:57:9)
  at FileWriter.extend.writeFile (/Users/employee/projects/jehoshua02/react-scaffold/node_modules/jest-cli/node_modules/istanbul/lib/util/file-writer.js:147:23)
  at /Users/employee/projects/jehoshua02/react-scaffold/node_modules/jest-cli/node_modules/istanbul/lib/report/html.js:471:24
  at Array.forEach (native)
  at HtmlReport.Report.mix.writeFiles (/Users/employee/projects/jehoshua02/react-scaffold/node_modules/jest-cli/node_modules/istanbul/lib/report/html.js:465:23)
  at /Users/employee/projects/jehoshua02/react-scaffold/node_modules/jest-cli/node_modules/istanbul/lib/report/html.js:467:22
  at Array.forEach (native)
  at HtmlReport.Report.mix.writeFiles (/Users/employee/projects/jehoshua02/react-scaffold/node_modules/jest-cli/node_modules/istanbul/lib/report/html.js:465:23)
  at HtmlReport.Report.mix.writeReport (/Users/employee/projects/jehoshua02/react-scaffold/node_modules/jest-cli/node_modules/istanbul/lib/report/html.js:549:14)
  at LcovReport.Report.mix.writeReport (/Users/employee/projects/jehoshua02/react-scaffold/node_modules/jest-cli/node_modules/istanbul/lib/report/lcov.js:55:19)
  at /Users/employee/projects/jehoshua02/react-scaffold/node_modules/jest-cli/node_modules/istanbul/lib/reporter.js:93:20
  at Array.forEach (native)
  at Object.Reporter.write (/Users/employee/projects/jehoshua02/react-scaffold/node_modules/jest-cli/node_modules/istanbul/lib/reporter.js:87:30)
  at DefaultTestReporter.IstanbulTestReporter.onRunComplete (/Users/employee/projects/jehoshua02/react-scaffold/node_modules/jest-cli/src/IstanbulTestReporter.js:33:14)
  at /Users/employee/projects/jehoshua02/react-scaffold/node_modules/jest-cli/src/TestRunner.js:453:40
  at _fulfilled (/Users/employee/projects/jehoshua02/react-scaffold/node_modules/jest-cli/node_modules/q/q.js:798:54)
  at self.promiseDispatch.done (/Users/employee/projects/jehoshua02/react-scaffold/node_modules/jest-cli/node_modules/q/q.js:827:30)
  at Promise.promise.promiseDispatch (/Users/employee/projects/jehoshua02/react-scaffold/node_modules/jest-cli/node_modules/q/q.js:760:13)
  at /Users/employee/projects/jehoshua02/react-scaffold/node_modules/jest-cli/node_modules/q/q.js:574:44
  at flush (/Users/employee/projects/jehoshua02/react-scaffold/node_modules/jest-cli/node_modules/q/q.js:108:17)
  at process._tickCallback (node.js:442:13)

npm ERR! Test failed.  See above for more details.
```

**Comment by jehoshua02** [comment]
It outputs coverage to the console beautifully and that's really all I want. I wonder if I can disable whatever else is going on?

**Comment by csaintc** [comment]
:+1:
