### ISSUE TITLE
Running into an error: Duplicate data property in object literal not allowed in strict mode

### ISSUE THREAD

**Issue by hasAnnaA** [babel/babel-jest#3]
Full stack trace:

```
SyntaxError: /Users/me/Documents/delphi-components/delphi_components/pager/PageSizeControl.jsx: Duplicate data property in object literal not allowed in strict mode
      at Contextify.sandbox.run (/Users/me/Documents/delphi-components/node_modules/jest-cli/node_modules/jsdom/node_modules/contextify/lib/contextify.js:12:24)
      at JSDomEnvironment.runSourceText (/Users/me/Documents/delphi-components/node_modules/jest-cli/src/JSDomEnvironment.js:106:22)
      at Object.runContentWithLocalBindings (/Users/me/Documents/delphi-components/node_modules/jest-cli/src/lib/utils.js:341:23)
      at Loader._execModule (/Users/me/Documents/delphi-components/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:245:9)
      at Loader.requireModule (/Users/me/Documents/delphi-components/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:900:12)
      at Loader.requireModuleOrMock (/Users/me/Documents/delphi-components/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:921:17)
      at Suite.<anonymous> (/Users/me/Documents/delphi-components/delphi_components/pager/__tests__/PageSizeControl-test.js:7:25)
      at env.describe_ (<anonymous>:40:25)
      at env.describe (<anonymous>:27:19)
      at describe (/Users/me/Documents/delphi-components/node_modules/jest-cli/vendor/jasmine/jasmine-1.3.0.js:604:27)
      at /Users/me/Documents/delphi-components/delphi_components/pager/__tests__/PageSizeControl-test.js:5:1
      at Object.runContentWithLocalBindings (/Users/me/Documents/delphi-components/node_modules/jest-cli/src/lib/utils.js:357:17)
      at Loader._execModule (/Users/me/Documents/delphi-components/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:245:9)
      at Loader.requireModule (/Users/me/Documents/delphi-components/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:900:12)
      at jasmineTestRunner (/Users/me/Documents/delphi-components/node_modules/jest-cli/src/jasmineTestRunner/jasmineTestRunner.js:239:16)
      at /Users/me/Documents/delphi-components/node_modules/jest-cli/src/TestRunner.js:371:12
      at _fulfilled (/Users/me/Documents/delphi-components/node_modules/jest-cli/node_modules/q/q.js:798:54)
      at self.promiseDispatch.done (/Users/me/Documents/delphi-components/node_modules/jest-cli/node_modules/q/q.js:827:30)
      at Promise.promise.promiseDispatch (/Users/me/Documents/delphi-components/node_modules/jest-cli/node_modules/q/q.js:760:13)
      at /Users/me/Documents/delphi-components/node_modules/jest-cli/node_modules/q/q.js:574:44
      at flush (/Users/me/Documents/delphi-components/node_modules/jest-cli/node_modules/q/q.js:108:17)
      at /Users/me/Documents/delphi-components/node_modules/jest-cli/src/lib/FakeTimers.js:259:7
      at process._tickCallback (node.js:419:13)
```

Let me know if you need more info from me!

**Comment by hasAnnaA** [comment]
Any updates on this?

**Comment by sebmck** [comment]
@hasAnnaA Sorry for taking so long to get back to you. This isn't really a 6to5 issue, basically your file in `/Users/me/Documents/delphi-components/delphi_components/pager/PageSizeControl.jsx` is being passed to 6to5. It assumes that it's ES6 and duplicate properties are illegal. Duplicate properties are actually useless and the first one has no effect, so it's likely a bug in your code.

**Comment by benjamingr** [comment]
@sebmck not sure if related but actually duplicate properties are illegal in strict mode in ES5 but legal in ES6, funstuff.
