### ISSUE TITLE
Exclude bower files from includes

### ISSUE THREAD

**Issue by MathRobin** [babel/babel-jest#31]
Hi !

I see in code that node_modules files are excluded. How can I exclude bower_components files ?

I get this kind of error :

 FAIL  bower_components/ngTools.Notify/tests/service.js (0.128s)
● Service : Notify › it encountered a declaration exception
  - TypeError: object is not a function
        at Suite.<anonymous> (/myproj/bower_components/ngTools.Notify/tests/service.js:8:16)
        at env.describe_ (<anonymous>:40:25)
        at env.describe (<anonymous>:27:19)
        at describe (/myproj/node_modules/jest-cli/vendor/jasmine/jasmine-1.3.0.js:604:27)
        at /myproj/bower_components/ngTools.Notify/tests/service.js:3:1

**Comment by silentroach** [comment]
You can use `preprocessorIgnorePatterns` jest config option

**Comment by MathRobin** [comment]
Oh great, thanks :-D
