### ISSUE TITLE
requiring react from test silently fails with iojs

### ISSUE THREAD

**Issue by neojski** [babel/babel-jest#36]
After issue #35 I installed iojs (v3.0.0). But the following fails: 

```js
// __tests__/sum-test.js
jest.dontMock('../sum');

describe('sum', function() {
 it('adds 1 + 2 to equal 3', function() {
   require('react');
   var sum = require('../sum');
   expect(sum(1, 2)).toBe(3);
 }); 
});
```

with a long error:
```

> @ test /home/neo/asdf
> jest

Using Jest CLI v0.4.17
Waiting on 1 test...
 FAIL  __tests__/test.js (0.507s)
● sum › it adds 1 + 2 to equal 3
  - TypeError: /home/neo/asdf/node_modules/react/addons.js: /home/neo/asdf/node_modules/react/lib/ReactWithAddons.js: /home/neo/asdf/node_modules/react/lib/LinkedStateMixin.js: /home/neo/asdf/node_modules/react/lib/ReactLink.js: /home/neo/asdf/node_modules/react/lib/React.js: /home/neo/asdf/node_modules/react/lib/ReactComponent.js: /home/neo/asdf/node_modules/react/lib/ReactUpdateQueue.js: /home/neo/asdf/node_modules/react/lib/ReactUpdates.js: CallbackQueue.getPooled is not a function
        at Object.<anonymous> (/home/neo/asdf/node_modules/react/lib/ReactUpdates.js:26:39)
        at Object.runContentWithLocalBindings (/home/neo/asdf/node_modules/jest-cli/src/lib/utils.js:495:17)
        at Loader._execModule (/home/neo/asdf/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:236:9)
        at Loader.requireModule (/home/neo/asdf/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:905:12)
        at Loader._generateMock (/home/neo/asdf/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:267:30)
        at Loader.requireMock (/home/neo/asdf/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:801:43)
        at Loader.requireModuleOrMock (/home/neo/asdf/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:924:17)
        at Object.<anonymous> (/home/neo/asdf/node_modules/react/lib/ReactUpdateQueue.js:18:20)
        at Object.runContentWithLocalBindings (/home/neo/asdf/node_modules/jest-cli/src/lib/utils.js:495:17)
        at Loader._execModule (/home/neo/asdf/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:236:9)
        at Loader.requireModule (/home/neo/asdf/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:905:12)
        at Loader._generateMock (/home/neo/asdf/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:267:30)
        at Loader.requireMock (/home/neo/asdf/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:801:43)
        at Loader.requireModuleOrMock (/home/neo/asdf/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:924:17)
        at Object.<anonymous> (/home/neo/asdf/node_modules/react/lib/ReactComponent.js:14:24)
        at Object.runContentWithLocalBindings (/home/neo/asdf/node_modules/jest-cli/src/lib/utils.js:495:17)
        at Loader._execModule (/home/neo/asdf/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:236:9)
        at Loader.requireModule (/home/neo/asdf/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:905:12)
        at Loader._generateMock (/home/neo/asdf/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:267:30)
        at Loader.requireMock (/home/neo/asdf/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:801:43)
        at Loader.requireModuleOrMock (/home/neo/asdf/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:924:17)
        at Object.<anonymous> (/home/neo/asdf/node_modules/react/lib/React.js:18:22)
        at Object.runContentWithLocalBindings (/home/neo/asdf/node_modules/jest-cli/src/lib/utils.js:495:17)
        at Loader._execModule (/home/neo/asdf/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:236:9)
        at Loader.requireModule (/home/neo/asdf/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:905:12)
        at Loader._generateMock (/home/neo/asdf/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:267:30)
        at Loader.requireMock (/home/neo/asdf/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:801:43)
        at Loader.requireModuleOrMock (/home/neo/asdf/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:924:17)
        at Object.<anonymous> (/home/neo/asdf/node_modules/react/lib/ReactLink.js:38:13)
        at Object.runContentWithLocalBindings (/home/neo/asdf/node_modules/jest-cli/src/lib/utils.js:495:17)
        at Loader._execModule (/home/neo/asdf/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:236:9)
        at Loader.requireModule (/home/neo/asdf/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:905:12)
        at Loader._generateMock (/home/neo/asdf/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:267:30)
        at Loader.requireMock (/home/neo/asdf/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:801:43)
        at Loader.requireModuleOrMock (/home/neo/asdf/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:924:17)
        at Object.<anonymous> (/home/neo/asdf/node_modules/react/lib/LinkedStateMixin.js:15:17)
        at Object.runContentWithLocalBindings (/home/neo/asdf/node_modules/jest-cli/src/lib/utils.js:495:17)
        at Loader._execModule (/home/neo/asdf/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:236:9)
        at Loader.requireModule (/home/neo/asdf/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:905:12)
        at Loader._generateMock (/home/neo/asdf/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:267:30)
        at Loader.requireMock (/home/neo/asdf/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:801:43)
        at Loader.requireModuleOrMock (/home/neo/asdf/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:924:17)
        at Object.<anonymous> (/home/neo/asdf/node_modules/react/lib/ReactWithAddons.js:21:24)
        at Object.runContentWithLocalBindings (/home/neo/asdf/node_modules/jest-cli/src/lib/utils.js:495:17)
        at Loader._execModule (/home/neo/asdf/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:236:9)
        at Loader.requireModule (/home/neo/asdf/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:905:12)
        at Loader._generateMock (/home/neo/asdf/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:267:30)
        at Loader.requireMock (/home/neo/asdf/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:801:43)
        at Loader.requireModuleOrMock (/home/neo/asdf/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:924:17)
        at Object.<anonymous> (/home/neo/asdf/node_modules/react/addons.js:1:115)
        at Object.runContentWithLocalBindings (/home/neo/asdf/node_modules/jest-cli/src/lib/utils.js:495:17)
        at Loader._execModule (/home/neo/asdf/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:236:9)
        at Loader.requireModule (/home/neo/asdf/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:905:12)
        at Loader._generateMock (/home/neo/asdf/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:267:30)
        at Loader.requireMock (/home/neo/asdf/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:801:43)
        at Loader.requireModuleOrMock (/home/neo/asdf/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:924:17)
        at Spec.<anonymous> (/home/neo/asdf/__tests__/test.js:6:5)
        at jasmine.Block.execute (/home/neo/asdf/node_modules/jest-cli/vendor/jasmine/jasmine-1.3.0.js:1065:17)
        at jasmine.Queue.next_ (/home/neo/asdf/node_modules/jest-cli/vendor/jasmine/jasmine-1.3.0.js:2098:31)
        at null._onTimeout (/home/neo/asdf/node_modules/jest-cli/vendor/jasmine/jasmine-1.3.0.js:2088:18)
        at Timer.listOnTimeout (timers.js:89:15)
1 test failed, 0 tests passed (1 total)
Run time: 0.806s
npm ERR! Test failed.  See above for more details.
```

I'm not sure but it looks to me like `jest` is trying to mock `react` but it fails to do so. I tried to tell it to `jest.dontMock('react')` but with no difference.

Just a side-note: I normally use `gulp` to bundle my scripts with `browserify` that uses babel with config in `package.json` (babelify).

**Comment by zertosh** [comment]
jest 0.5.x doesn't even install with iojs 3.0.0 because contextify (one of its deps) doesn't compile under 3.0.0. you're probably using a jest that compiled with another version of iojs/node. I recommend that you remove jest, remove iojs 3.0.0, install iojs 2.5.0, reinstall jest (so it compiles with iojs 2.5.0), and then try to run the tests.

**Comment by sebmck** [comment]
Have you tried it in normal jest? I don't see how `babel-jest` can effect this.

**Comment by zertosh** [comment]
When you install jest, use `npm install "facebook/jest#0.5.x"` (see https://github.com/facebook/jest/pull/374)

**Comment by greg5green** [comment]
I'm having this same issue with iojs 2.5.0, Jest-CLI 0.5.2, Babel-Jest 5.3.0 and Babel 5.8.23. I think it's an issue with Babel or Jest rather than Babel-Jest, but it might be an issue with the options being passed into Babel? I'm trying to investigate further now.

**Comment by petejkim** [comment]
@greg5green same here

**Comment by petejkim** [comment]
Adding the following solved the problem for me:

**package.json:**

```json
"jest": {
  ...
  "unmockedModulePathPatterns": ["<rootDir>/node_modules/react"]
```

**Comment by greg5green** [comment]
I don't think I had that in my package.json, but I moved a different direction and dont have the code I was working on committed so I can't confirm. I'll have to backtrack when I have some free time Friday to see if that solves it for me too.

I'm guessing you could probably close this @sebmck now that I've necro'd this issue.

**Comment by boourns** [comment]
following @petekjim's advice fixed the problem for me (in case anyone else arrives here via google :) )

**Comment by jstejada** [comment]
same for me. @boourns

**Comment by andrey-messi** [comment]
*"unmockedModulePathPatterns": ["< rootDir>/node_modules/react"]* still doesn't work for me. I have 
  *"jest": { 
	"scriptPreprocessor": "< rootDir>/node_modules/babel-jest",
	"unmockedModulePathPatterns": ["< rootDir>/node_modules/react"] 
  }*
in my package.json and still get error "CallbackQueue.getPooled is not a function" (I added space between '<' and 'rootDir' here in my post just for it to not being cut by a forum engine). What should I do?

**Comment by andrey-messi** [comment]
Found a solution. For me it works:
  *"jest": { 
	"scriptPreprocessor": "< rootDir>/node_modules/babel-jest",
	"unmockedModulePathPatterns": ["react"] 
  }*

**Comment by mkapnick** [comment]
Thank you @petejkim
