### ISSUE TITLE
Cannot import ES6 module

### ISSUE THREAD

**Issue by inf3rno** [babel/babel-jest#42]
I try to run jest with `jest --config=jest.conf.json` from an npm script on a project template.

jest.conf.json

```js
{
  "scriptPreprocessor": "./node_modules/babel-jest",
  "testFileExtensions": [
    "js"
  ],
  "moduleFileExtensions": [
    "js",
    "json"
  ],
  "testDirectoryName": "spec"
}
```

the first file it tries to run is spec/multiplication.spec.js

```js
import {multiply} from "../src/multiplication.js";

describe("multiply", function () {

    it("returns the product of the given numbers", function () {
        expect(multiply(1, 2)).toBe(2);
        expect(multiply(2, 3, 4)).toBe(24);
    });

});
```

it imports from src/multiplication.js

```js
export function multiply() {
    var result = 1;
    for (var i = 0; i < arguments.length; ++i)
        result *= arguments[i];
    return result;
}
```

I got the following log

```js
D:\creation\software developer\projects\javascript-project-template>npm run test-node

> math-template@0.1.0 test-node D:\creation\software developer\projects\javascript-project-template
> jest --config=jest.conf.json

Using Jest CLI v0.6.0
 FAIL  spec\multiplication.spec.js (1.015s)
? multiply > it returns the product of the given numbers
  - Expected: undefined toBe: 2
        at new jasmine.ExpectationResult (node_modules\jest-cli\vendor\jasmine\jasmine-1.3.0.js:115:32)
        at null.toBe (node_modules\jest-cli\vendor\jasmine\jasmine-1.3.0.js:1238:29)
        at Spec.<anonymous> (spec\multiplication.spec.js:6:58)
        at jasmine.Block.execute (node_modules\jest-cli\vendor\jasmine\jasmine-1.3.0.js:1067:17)
        at jasmine.Queue.next_ (node_modules\jest-cli\vendor\jasmine\jasmine-1.3.0.js:2100:31)
        at null._onTimeout (node_modules\jest-cli\vendor\jasmine\jasmine-1.3.0.js:2090:18)
  - Expected: undefined toBe: 24
        at new jasmine.ExpectationResult (node_modules\jest-cli\vendor\jasmine\jasmine-1.3.0.js:115:32)
        at null.toBe (node_modules\jest-cli\vendor\jasmine\jasmine-1.3.0.js:1238:29)
        at Spec.<anonymous> (spec\multiplication.spec.js:7:61)
        at jasmine.Block.execute (node_modules\jest-cli\vendor\jasmine\jasmine-1.3.0.js:1067:17)
        at jasmine.Queue.next_ (node_modules\jest-cli\vendor\jasmine\jasmine-1.3.0.js:2100:31)
        at null._onTimeout (node_modules\jest-cli\vendor\jasmine\jasmine-1.3.0.js:2090:18)
 FAIL  spec\division.spec.js (0.935s)
? divide > it returns the quotient of 2 numbers
  - Expected: undefined toBe: 2
        at new jasmine.ExpectationResult (node_modules\jest-cli\vendor\jasmine\jasmine-1.3.0.js:115:32)
        at null.toBe (node_modules\jest-cli\vendor\jasmine\jasmine-1.3.0.js:1238:29)
        at Spec.<anonymous> (spec\division.spec.js:6:50)
        at jasmine.Block.execute (node_modules\jest-cli\vendor\jasmine\jasmine-1.3.0.js:1067:17)
        at jasmine.Queue.next_ (node_modules\jest-cli\vendor\jasmine\jasmine-1.3.0.js:2100:31)
        at null._onTimeout (node_modules\jest-cli\vendor\jasmine\jasmine-1.3.0.js:2090:18)
  - Expected: undefined toBe: 0.5
        at new jasmine.ExpectationResult (node_modules\jest-cli\vendor\jasmine\jasmine-1.3.0.js:115:32)
        at null.toBe (node_modules\jest-cli\vendor\jasmine\jasmine-1.3.0.js:1238:29)
        at Spec.<anonymous> (spec\division.spec.js:7:50)
        at jasmine.Block.execute (node_modules\jest-cli\vendor\jasmine\jasmine-1.3.0.js:1067:17)
        at jasmine.Queue.next_ (node_modules\jest-cli\vendor\jasmine\jasmine-1.3.0.js:2100:31)
        at null._onTimeout (node_modules\jest-cli\vendor\jasmine\jasmine-1.3.0.js:2090:18)
 FAIL  spec\math.spec.js (0.984s)
? math > it describes four basic operations
  - Expected: undefined toBe: 13
        at new jasmine.ExpectationResult (node_modules\jest-cli\vendor\jasmine\jasmine-1.3.0.js:115:32)
        at null.toBe (node_modules\jest-cli\vendor\jasmine\jasmine-1.3.0.js:1238:29)
        at Spec.<anonymous> (spec\math.spec.js:6:151)
        at jasmine.Block.execute (node_modules\jest-cli\vendor\jasmine\jasmine-1.3.0.js:1067:17)
        at jasmine.Queue.next_ (node_modules\jest-cli\vendor\jasmine\jasmine-1.3.0.js:2100:31)
        at null._onTimeout (node_modules\jest-cli\vendor\jasmine\jasmine-1.3.0.js:2090:18)
 FAIL  spec\addition.spec.js (0.026s)
? add > it returns the summary of the given numbers
  - Expected: undefined toBe: 3
        at new jasmine.ExpectationResult (node_modules\jest-cli\vendor\jasmine\jasmine-1.3.0.js:115:32)
        at null.toBe (node_modules\jest-cli\vendor\jasmine\jasmine-1.3.0.js:1238:29)
        at Spec.<anonymous> (spec\addition.spec.js:6:47)
        at jasmine.Block.execute (node_modules\jest-cli\vendor\jasmine\jasmine-1.3.0.js:1067:17)
        at jasmine.Queue.next_ (node_modules\jest-cli\vendor\jasmine\jasmine-1.3.0.js:2100:31)
        at null._onTimeout (node_modules\jest-cli\vendor\jasmine\jasmine-1.3.0.js:2090:18)
  - Expected: undefined toBe: 9
        at new jasmine.ExpectationResult (node_modules\jest-cli\vendor\jasmine\jasmine-1.3.0.js:115:32)
        at null.toBe (node_modules\jest-cli\vendor\jasmine\jasmine-1.3.0.js:1238:29)
        at Spec.<anonymous> (spec\addition.spec.js:7:50)
        at jasmine.Block.execute (node_modules\jest-cli\vendor\jasmine\jasmine-1.3.0.js:1067:17)
        at jasmine.Queue.next_ (node_modules\jest-cli\vendor\jasmine\jasmine-1.3.0.js:2100:31)
        at null._onTimeout (node_modules\jest-cli\vendor\jasmine\jasmine-1.3.0.js:2090:18)
 PASS  spec\subtraction.spec.js (0.967s)
4 tests failed, 1 test passed (5 total in 5 test suites, run time 4.051s)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\inf3rno\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "test-node"
npm ERR! node v4.2.1
npm ERR! npm  v2.11.1
npm ERR! code ELIFECYCLE
npm ERR! math-template@0.1.0 test-node: `jest --config=jest.conf.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the math-template@0.1.0 test-node script 'jest --config=jest.conf.json'.
npm ERR! This is most likely a problem with the math-template package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     jest --config=jest.conf.json
npm ERR! You can get their info via:
npm ERR!     npm owner ls math-template
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\creation\software developer\projects\javascript-project-template\npm-debug.log
```

The same code works with karma+browserify+babelify+jasmine.

**Comment by kuitos** [comment]
see https://github.com/babel/babel-jest/issues/16

**Comment by genechan** [comment]
The workaround in #16 doesn't work, or just no longer works.
It fails at runtime reading the import
● Runtime Error
SyntaxError: Unexpected token import

you can see @Rauschmayer example of the work around at 
https://github.com/rauschma/babel-on-node

and see it fail.

I hope this will be fixed soon.

**Comment by nhz-io** [comment]
Fastest fix: `const multiply = require('../src/multiplication.js').multiply;`

**Comment by jamedranoa** [comment]
@inf3rno is that all you have in `spec/multiplication.spec.js`? based on you jest config, I think jest is mocking your `multiplication.js` module.

**Comment by cpojer** [comment]
This will be fixed in https://github.com/facebook/jest/pull/741 for 0.9.0.

**Comment by inf3rno** [comment]
@jamedranoa It's just a project template, btw. I no longer use that kind of stuff, I just tried out babel. I think I'll wait out native ES6 support, compiling was too slow. :-)
